apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
spec:
  addresses:
  - 192.168.20.2-192.168.20.2
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: all