expose:
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: ${harbor_domain}
    className: nginx
    annotations:
      cert-manager.io/issuer: step-issuer
      cert-manager.io/issuer-group: certmanager.step.sm
      cert-manager.io/issuer-kind: StepClusterIssuer
externalURL: ${harbor_url}
persistence:
  persistentVolumeClaim:
    registry:
      size: 200Gi
    jobservice:
      jobLog:
        size: 5Gi
    database:
      size: 5Gi
    redis:
      size: 5Gi
    trivy:
      size: 5Gi
existingSecretAdminPassword: "harbor-admin"
imagePullSecrets:
  - name: docker-registry-secret